name = "macabre_sqlight"
version = "1.2.0"
licences = ["Apache-2.0"]
description = "Use SQLite from Gleam (macabre python-target fork of sqlight)"

gleam = ">= 1.15.0"

repository = { type = "github", user = "dusty-phillips", repo = "macabre_sqlight" }
links = [
    { title = "Website", href = "https://gleam.run" },
    { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = { git = "git@github.com:dusty-phillips/macabre_stdlib.git", ref = "main" }

[dev-dependencies]
gleeunit = { git = "git@github.com:dusty-phillips/macabre_gleeunit.git", ref = "main" }
